; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.clusterlaunchcontrol.query_cancel.get_first_ctaid.y(i128)

define i32 @probe_clc_query_get_first_ctaid_y(i64 %response_low, i64 %response_high) {
  %response_low_i128 = zext i64 %response_low to i128
  %response_high_i128 = zext i64 %response_high to i128
  %response_high_shifted = shl i128 %response_high_i128, 64
  %response = or i128 %response_low_i128, %response_high_shifted
  %raw_result = call i32 @llvm.nvvm.clusterlaunchcontrol.query_cancel.get_first_ctaid.y(i128 %response)
  ret i32 %raw_result
}
