; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.ca.shared.global.4(ptr addrspace(3), ptr addrspace(1))

define void @probe_cp_async_ca_4(ptr %shared_generic, ptr %global_generic) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.4(ptr addrspace(3) %shared, ptr addrspace(1) %global)
  ret void
}
