; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1c4e9feb5d4c2ffb4b8d6cf7b44dc658cfc2858fcb3cbd744e4e14280822e790.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.ca.shared.global.16.s(ptr addrspace(3), ptr addrspace(1), i32)

define void @probe_cp_async_ca_zfill_16_register(ptr %shared_generic, ptr %global_generic, i32 %source_size) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.16.s(ptr addrspace(3) %shared, ptr addrspace(1) %global, i32 %source_size)
  ret void
}
define void @probe_cp_async_ca_zfill_16_immediate(ptr %shared_generic, ptr %global_generic) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.16.s(ptr addrspace(3) %shared, ptr addrspace(1) %global, i32 3)
  ret void
}
