; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1c4e9feb5d4c2ffb4b8d6cf7b44dc658cfc2858fcb3cbd744e4e14280822e790.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_min_ftz_xorsign_abs_f16(i16 %a, i16 %b) {
  %result = call i16 asm "min.ftz.xorsign.abs.f16 $0, $1, $2;", "=h,h,h"(i16 %a, i16 %b)
  ret i16 %result
}
