; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1c4e9feb5d4c2ffb4b8d6cf7b44dc658cfc2858fcb3cbd744e4e14280822e790.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define float @probe_min_ftz_nan_xorsign_abs_f32(float %a, float %b) {
  %result = call float asm "min.ftz.NaN.xorsign.abs.f32 $0, $1, $2;", "=f,f,f"(float %a, float %b)
  ret float %result
}
