; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_shuffle_up_u64_sync(i32 %member_mask, i64 %value, i32 %lane) #0 {
  %result = call i64 asm sideeffect "{ .reg .b32 lo; .reg .b32 hi; mov.b64 {lo, hi}, $1; shfl.sync.up.b32 lo, lo, $2, 0, $3; shfl.sync.up.b32 hi, hi, $2, 0, $3; mov.b64 $0, {lo, hi}; }", "=l,l,r,r"(i64 %value, i32 %lane, i32 %member_mask) #0
  ret i64 %result
}

attributes #0 = { convergent }
