; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare float @llvm.nvvm.shfl.sync.idx.f32(i32, float, i32, i32)

define float @probe_shuffle_f32_sync_rr(i32 %member_mask, float %value, i32 %lane) {
  %result = call float @llvm.nvvm.shfl.sync.idx.f32(i32 %member_mask, float %value, i32 %lane, i32 31)
  ret float %result
}
define float @probe_shuffle_f32_sync_ri(float %value, i32 %lane) {
  %result = call float @llvm.nvvm.shfl.sync.idx.f32(i32 -1, float %value, i32 %lane, i32 31)
  ret float %result
}
define float @probe_shuffle_f32_sync_ir(i32 %member_mask, float %value) {
  %result = call float @llvm.nvvm.shfl.sync.idx.f32(i32 %member_mask, float %value, i32 1, i32 31)
  ret float %result
}
define float @probe_shuffle_f32_sync_ii(float %value) {
  %result = call float @llvm.nvvm.shfl.sync.idx.f32(i32 -1, float %value, i32 1, i32 31)
  ret float %result
}
