; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1c4e9feb5d4c2ffb4b8d6cf7b44dc658cfc2858fcb3cbd744e4e14280822e790.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.stmatrix.sync.aligned.m8n8.x4.trans.b16.p3(ptr addrspace(3), i32, i32, i32, i32)

define void @probe_stmatrix_m8n8_x4_trans_b16(ptr %generic, i32 %r0, i32 %r1, i32 %r2, i32 %r3) {
  %shared = addrspacecast ptr %generic to ptr addrspace(3)
  call void @llvm.nvvm.stmatrix.sync.aligned.m8n8.x4.trans.b16.p3(ptr addrspace(3) %shared, i32 %r0, i32 %r1, i32 %r2, i32 %r3)
  ret void
}
