; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.mma.sp.shared; route: inline PTX; source contract: TablegenSelectionChangesPtx
define void @probe_tcgen05_mma_sp_shared(i32 %d_tmem, i64 %a_desc, i64 %b_desc, i32 %idesc, i1 %enable_d, i32 %metadata_tmem) #0 {
  call void asm sideeffect "{ .reg .pred %enable_pred; setp.ne.s32 %enable_pred, $4, 0; tcgen05.mma.sp.cta_group::1.kind::f16.collector::a::discard [$0], $1, $2, [$5], $3, %enable_pred; }", "r,l,l,r,r,r,~{memory}"(i32 %d_tmem, i64 %a_desc, i64 %b_desc, i32 %idesc, i1 %enable_d, i32 %metadata_tmem) #0
  ret void
}

attributes #0 = { convergent }
