; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.alloc.shared.cg2; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_alloc_cg2(ptr %dst, i32 %ncols) #0 {
  call void asm sideeffect "{ .reg .u64 %shared64; .reg .u32 %shared32; cvta.to.shared.u64 %shared64, $0; cvt.u32.u64 %shared32, %shared64; tcgen05.alloc.cta_group::2.sync.aligned.shared::cta.b32 [%shared32], $1; }", "l,r,~{memory}"(ptr %dst, i32 %ncols) #0
  ret void
}

attributes #0 = { convergent }
