; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 1c4e9feb5d4c2ffb4b8d6cf7b44dc658cfc2858fcb3cbd744e4e14280822e790.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.wait.st; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_store_wait() #0 {
  call void asm sideeffect "tcgen05.wait::st.sync.aligned;", "~{memory}"() #0
  ret void
}

attributes #0 = { convergent }
