; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 92999ce39ed0f26c69d04601dbba47e6a7ccc3d1a5e60abb695f0e09cb371ed4.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i1 @llvm.nvvm.vote.uni.sync(i32, i1)

define i1 @probe_uni_sync(i32 %member_mask, i1 %predicate) {
  %result = call i1 @llvm.nvvm.vote.uni.sync(i32 %member_mask, i1 %predicate)
  ret i1 %result
}
define i1 @probe_uni_sync_immediate(i1 %predicate) {
  %result = call i1 @llvm.nvvm.vote.uni.sync(i32 -1, i1 %predicate)
  ret i1 %result
}
